// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Discover() {
  return window['go']['main']['App']['Discover']();
}

export function Heartbeat() {
  return window['go']['main']['App']['Heartbeat']();
}

export function NodeURL() {
  return window['go']['main']['App']['NodeURL']();
}

export function Overview() {
  return window['go']['main']['App']['Overview']();
}

export function SetNodeURL(arg1) {
  return window['go']['main']['App']['SetNodeURL'](arg1);
}

export function SetVisibility(arg1, arg2) {
  return window['go']['main']['App']['SetVisibility'](arg1, arg2);
}
