// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearInbox(arg1:string):Promise<main.ClearedInbox>;

export function ClosePairing():Promise<main.PairingState>;

export function CopyText(arg1:string):Promise<void>;

export function Discover():Promise<Record<string, number>>;

export function Heartbeat():Promise<string>;

export function Inbox(arg1:string):Promise<main.InboxView>;

export function InstallService(arg1:main.ServiceForm):Promise<main.ServiceResult>;

export function LocalAddresses():Promise<Array<main.LocalAddress>>;

export function MCPConfig(arg1:string):Promise<main.MCPConfigResult>;

export function NodeURL():Promise<string>;

export function OpenPairing(arg1:number):Promise<main.PairingState>;

export function Outbound(arg1:number,arg2:string):Promise<main.OutboundView>;

export function Overview():Promise<main.Overview>;

export function Pairing():Promise<main.Pairing>;

export function RevokeNode(arg1:string):Promise<void>;

export function ServiceStatus():Promise<main.ServiceStatus>;

export function SetAudience(arg1:Array<string>,arg2:main.Audience):Promise<main.VisibilityResult>;

export function SetNodeAddress(arg1:string,arg2:string):Promise<void>;

export function SetNodeURL(arg1:string):Promise<void>;

export function SetVisibility(arg1:Array<string>,arg2:string):Promise<main.VisibilityResult>;

export function TrustNode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.TrustedNode>;

export function UninstallService():Promise<main.ServiceResult>;

export function Wakes(arg1:string,arg2:number):Promise<main.WakesView>;
