// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Discover():Promise<Record<string, number>>;

export function Heartbeat():Promise<string>;

export function NodeURL():Promise<string>;

export function Overview():Promise<main.Overview>;

export function SetNodeURL(arg1:string):Promise<void>;

export function SetVisibility(arg1:Array<string>,arg2:string):Promise<main.VisibilityResult>;
