// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearInbox(arg1) {
  return window['go']['main']['App']['ClearInbox'](arg1);
}

export function ClosePairing() {
  return window['go']['main']['App']['ClosePairing']();
}

export function Discover() {
  return window['go']['main']['App']['Discover']();
}

export function Heartbeat() {
  return window['go']['main']['App']['Heartbeat']();
}

export function Inbox(arg1) {
  return window['go']['main']['App']['Inbox'](arg1);
}

export function InstallService(arg1) {
  return window['go']['main']['App']['InstallService'](arg1);
}

export function LocalAddresses() {
  return window['go']['main']['App']['LocalAddresses']();
}

export function MCPConfig(arg1) {
  return window['go']['main']['App']['MCPConfig'](arg1);
}

export function NodeURL() {
  return window['go']['main']['App']['NodeURL']();
}

export function OpenPairing(arg1) {
  return window['go']['main']['App']['OpenPairing'](arg1);
}

export function Overview() {
  return window['go']['main']['App']['Overview']();
}

export function Pairing() {
  return window['go']['main']['App']['Pairing']();
}

export function RevokeNode(arg1) {
  return window['go']['main']['App']['RevokeNode'](arg1);
}

export function ServiceStatus() {
  return window['go']['main']['App']['ServiceStatus']();
}

export function SetAudience(arg1, arg2) {
  return window['go']['main']['App']['SetAudience'](arg1, arg2);
}

export function SetNodeURL(arg1) {
  return window['go']['main']['App']['SetNodeURL'](arg1);
}

export function SetVisibility(arg1, arg2) {
  return window['go']['main']['App']['SetVisibility'](arg1, arg2);
}

export function TrustNode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TrustNode'](arg1, arg2, arg3, arg4, arg5);
}

export function UninstallService() {
  return window['go']['main']['App']['UninstallService']();
}
